service: rs-cart-api

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  profile: sandx
  region: eu-west-1
  environment:
    DATABASE_HOST: "${env:DATABASE_HOST}"
    DATABASE_PORT: "${env:DATABASE_PORT}"
    DATABASE_USERNAME: "${env:DATABASE_USERNAME}"
    DATABASE_PASSWORD: "${env:DATABASE_PASSWORD}"
    DATABASE_NAME: "${env:DATABASE_NAME}"

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: GET
          path: /ping
      - http:
          method: POST
          path: /api/auth/login
      - http:
          method: GET
          path: /api/profile
      - http:
          method: GET
          path: /api/profile/cart
      - http:
          method: POST
          path: /api/profile/cart
      - http:
          method: PUT
          path: /api/profile/cart
      - http:
          method: DELETE
          path: /api/profile/cart
      - http:
          method: POST
          path: /api/profile/cart/checkout